name: Run

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5.1.0
        with:
          python-version: "3.13"
      - run: uv run -m lerppu
      - run: touch output/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    needs: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
